from backend.models import Igrac
from .seeder import Seeder


def igraci_seeder():
    class SeederIgraci(Seeder):
        pass

    options = {
        'model': Igrac,
        'id_field': 'id_igraca',
    }

    data = [
        {
            'id_korisnika': 1,
            'ime_igraca': 'Root',
            'prezime_igraca': 'Admin',
            'srednje_ime': None,
            'datum_rodjenja': '1970-01-01',
            'spol': 1,
            'visina': 200,
            'tezina': 100,
            'nivo_sposobnosti': '0.9',
            'max_dozvoljena_udaljenost': 5,
            'verifikovan': 0,
            'recenzija': 5,
        },
        {
            'id_korisnika': 2,
            'ime_igraca': 'Pocetni',
            'prezime_igraca': 'Korisnik',
            'srednje_ime': None,
            'datum_rodjenja': '1970-01-01',
            'spol': 0,
            'visina': 170,
            'tezina': 60,
            'nivo_sposobnosti': '0.5',
            'max_dozvoljena_udaljenost': 4,
            'verifikovan': 0,
            'recenzija': 4,
        },
        {
            'id_korisnika': 4,
            'ime_igraca': 'Nejra',
            'prezime_igraca': 'Alickovic',
            'srednje_ime': None,
            'datum_rodjenja': '2001-05-20',
            'spol': 0,
            'visina': 170,
            'tezina': 60,
            'nivo_sposobnosti': '1',
            'max_dozvoljena_udaljenost': 4,
            'verifikovan': 1,
            'recenzija': 5,
        },
        {
            'id_korisnika': 5,
            'ime_igraca': 'Riad',
            'prezime_igraca': 'Pap',
            'srednje_ime': None,
            'datum_rodjenja': '1998-11-12',
            'spol': 1,
            'visina': 195,
            'tezina': 90,
            'nivo_sposobnosti': '0.8',
            'max_dozvoljena_udaljenost': 4,
            'verifikovan': 1,
            'recenzija': 5,
        },
        {
            'id_korisnika': 6,
            'ime_igraca': 'Emina',
            'prezime_igraca': 'Besic',
            'srednje_ime': None,
            'datum_rodjenja': '1970-01-01',
            'spol': 0,
            'visina': 170,
            'tezina': 60,
            'nivo_sposobnosti': '0.7',
            'max_dozvoljena_udaljenost': 4,
            'verifikovan': 1,
            'recenzija': 5,
        },
        {
            'id_korisnika': 7,
            'ime_igraca': 'Djeneta',
            'prezime_igraca': 'Velispahic',
            'srednje_ime': None,
            'datum_rodjenja': '1970-01-01',
            'spol': 0,
            'visina': 170,
            'tezina': 60,
            'nivo_sposobnosti': '0.8',
            'max_dozvoljena_udaljenost': 4,
            'verifikovan': 1,
            'recenzija': 5,
        },
        {
            'id_korisnika': 8,
            'ime_igraca': 'Matej',
            'prezime_igraca': 'Panic',
            'srednje_ime': None,
            'datum_rodjenja': '1970-01-01',
            'spol': 1,
            'visina': 180,
            'tezina': 80,
            'nivo_sposobnosti': '0.9',
            'max_dozvoljena_udaljenost': 4,
            'verifikovan': 1,
            'recenzija': 5,
        },
    ]

    SeederIgraci(options).seed(data)
